name: "Credly Badges Updater"
description: "Automatically fetch and update README with your Credly badges"
author: "hairbui76"
branding:
  icon: "award"
  color: "green"

inputs:
  CREDLY_USER:
    description: "Credly username"
    required: true
  GIT_COMMIT_MESSAGE:
    description: "Git commit message"
    required: false
    default: "Update Credly badges"
  GIT_USER_NAME:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  GIT_USER_EMAIL:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  BADGE_SIZE:
    description: "Size of badge images (width and height)"
    required: false
    default: "80"
  README_FILE:
    description: "README file name"
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - name: Install dependencies
      run: |
        cd ${{ github.action_path }}
        npm ci --production
      shell: bash
    - name: Run action
      run: node index.js
      shell: bash
      env:
        INPUT_CREDLY_USER: ${{ inputs.CREDLY_USER }}
        INPUT_GIT_COMMIT_MESSAGE: ${{ inputs.GIT_COMMIT_MESSAGE }}
        INPUT_GIT_USER_NAME: ${{ inputs.GIT_USER_NAME }}
        INPUT_GIT_USER_EMAIL: ${{ inputs.GIT_USER_EMAIL }}
        INPUT_BADGE_SIZE: ${{ inputs.BADGE_SIZE }}
        INPUT_BADGE_STYLE: ${{ inputs.BADGE_STYLE }}
