name: "Credly Badges Updater"
description: "Automatically fetch and update README with your Credly badges"
author: "hairbui76"
branding:
  icon: "award"
  color: "green"

inputs:
  CREDLY_USER:
    description: "Credly username"
    required: true
  GIT_COMMIT_MESSAGE:
    description: "Git commit message"
    required: false
    default: "Update Credly badges"
  GIT_USER_NAME:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  GIT_USER_EMAIL:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  BADGE_SIZE:
    description: "Size of badge images (width and height)"
    required: false
    default: "80"
  README_FILE:
    description: "README file name"
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Checkout user's repository
      uses: actions/checkout@v4

    - name: Update badges using Docker
      id: update-badges
      shell: bash
      run: |
        # Create temporary directory for action files
        TEMP_DIR=$(mktemp -d)
        cp -r ${{ github.action_path }}/* $TEMP_DIR/

        # Run Docker with proper permissions
        docker run --rm \
          --user root \
          -v ${{ github.workspace }}:/workspace \
          -v $TEMP_DIR:/action \
          -w /workspace \
          -e INPUT_CREDLY_USER="${{ inputs.CREDLY_USER }}" \
          -e INPUT_BADGE_SIZE="${{ inputs.BADGE_SIZE }}" \
          -e INPUT_README_FILE="${{ inputs.README_FILE }}" \
          -e GITHUB_WORKSPACE="/workspace" \
          -e RUNNING_IN_DOCKER="true" \
          --entrypoint /bin/bash \
          ghcr.io/puppeteer/puppeteer:24.12.1 \
          -c "
            cd /action && \
            npm ci --production && \
            node index.js && \
            chown $(id -u):$(id -g) /workspace/${{ inputs.README_FILE }} 2>/dev/null || true
          "

    - name: Commit and push changes
      if: steps.update-badges.outputs.changes_made == 'true'
      shell: bash
      run: |
        git config --local user.name "${{ inputs.GIT_USER_NAME }}"
        git config --local user.email "${{ inputs.GIT_USER_EMAIL }}"
        git add ${{ inputs.README_FILE }}
        git commit -m "${{ inputs.GIT_COMMIT_MESSAGE }}"
        git push
