name: "Credly Badges Updater"
description: "Automatically fetch and update README with your Credly badges"
author: "hairbui76"
branding:
  icon: "award"
  color: "green"

inputs:
  CREDLY_USER:
    description: "Credly username"
    required: true
  GIT_COMMIT_MESSAGE:
    description: "Git commit message"
    required: false
    default: "Update Credly badges"
  GIT_USER_NAME:
    description: "Git user name for commits"
    required: false
    default: "github-actions[bot]"
  GIT_USER_EMAIL:
    description: "Git user email for commits"
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  BADGE_SIZE:
    description: "Size of badge images (width and height)"
    required: false
    default: "80"
  README_FILE:
    description: "README file name"
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Prepare action files
      shell: bash
      run: |
        # Copy action files to workspace
        cp -r ${{ github.action_path }}/* .

    - name: Run Puppeteer in Docker
      uses: docker://ghcr.io/puppeteer/puppeteer:latest
      with:
        args: |
          bash -c "
            cd /github/workspace &&
            npm ci --production &&
            node index.js
          "
      env:
        INPUT_CREDLY_USER: ${{ inputs.CREDLY_USER }}
        INPUT_BADGE_SIZE: ${{ inputs.BADGE_SIZE }}
        INPUT_README_FILE: ${{ inputs.README_FILE }}

    - name: Commit and push changes
      if: steps.check.outputs.changes_made == 'true'
      shell: bash
      run: |
        git config --local user.name "${{ inputs.GIT_USER_NAME }}"
        git config --local user.email "${{ inputs.GIT_USER_EMAIL }}"
        git add ${{ inputs.README_FILE }}
        git commit -m "${{ inputs.GIT_COMMIT_MESSAGE }}"
        git push
